---
## usage: ansible-playbook -i <inventory file> myplaybook.yml

- hosts: all 
  sudo: yes 
  vars:
    freeswitch_users:
      - fs_user_id: test01
        fs_user_password: pwstest01
      - fs_user_id: test02  
        fs_user_password: test02
    freeswitch_run_user: fsuser
    freeswitch_dir: /opt/freeswitch
    users:
      - username: fsuser 
        name: freeswitch users  
        home_dir: "{{freeswitch_dir}}" 
        password: "123"

  roles:
      - freeswitch-user  
      - freeswitch
      - freeswitch-service
      - freeswitch-iptables


#- hosts: node2
#  roles:
#    - ansible-fedora-virt

#  tasks:
#    - name: taskA
#      file: path=~/helloworld.txt state=touch
    
