---

# Create User on Freeswitch Server
#
#

- name: Generate password
  shell: openssl passwd -crypt -salt $$ prints
  register: gen_passwd
  
- debug: msg="{{gen_passwd}}"

- name: User creation
  user: name="{{item.username}}"
        group="{{item.username if users_create_per_user_group
            else users_group}}"
        home="{{item.home_dir}}"
        shell={{item.shell if item.shell is defined else users_default_shell}}
        password="{{gen_passwd.stdout if item.password is defined else '!'}}"
        comment="{{item.name}}"
        groups=daemon
        system=yes
        createhome="{{'yes' if users_create_homedirs else 'no'}}"
  with_items: users
  tags: ['users']






