---

- name: Insert iptables rule SSH Port
  lineinfile:
    dest=/etc/sysconfig/iptables 
    state=present 
    regexp="^.*INPUT.*tcp.*22.*ACCEPT" 
    insertafter="^.*INPUT.*ESTABLISHED,RELATED.*ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT" 
    backup=yes
  notify: restart iptables
  tags:
    - firewall 

- name: Insert iptables rule TCP 5060 Port
  lineinfile:
    dest=/etc/sysconfig/iptables
    state=present
    regexp="^.*INPUT.*tcp.*5060.*ACCEPT"
    insertafter="^.*INPUT.*ESTABLISHED,RELATED.*ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p tcp --dport 5060 -j ACCEPT"
    backup=yes
  notify: restart iptables
  tags:
    - firewall

- name: Insert iptables rule UDP 5060 Port
  lineinfile:
    dest=/etc/sysconfig/iptables
    state=present
    regexp="^.*INPUT.*udp.*5060.*ACCEPT"
    insertafter="^.*INPUT.*ESTABLISHED,RELATED.*ACCEPT" line="-A INPUT -m state --state NEW -m tcp -p udp --dport 5060 -j ACCEPT"
    backup=yes
  notify: restart iptables
  tags:
    - firewall

- name: DROP ALL
  lineinfile:
    dest=/etc/sysconfig/iptables
    state=present
    insertbefore="^COMMIT"
    line="-A INPUT -j DROP"
    backup=yes
  notify: restart iptables
  tags:
    - firewall

